package com.medallia.spider;

import java.util.Collection;
import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * Class that generates 'even' and 'odd' elements for a list. Typically used
 * for alternating rows in a table generated by StringTemplate.
 *
 */
public class EvenOddGenerator implements Iterator<String> {
	
	private final int count;
	private int i = 0;

	/** Generate values for the given collection */
	public EvenOddGenerator(Collection<?> c) {
		this(c.size());
	}
	/** Generate the given number of values */
	public EvenOddGenerator(int count) {
		this.count = count;
	}

	@Override
	public boolean hasNext() {
		return i < count;
	}
	
	@Override
	public String next() {
		if (!hasNext())
			throw new NoSuchElementException();
		
		i++;
		boolean even = (i & 1) == 0;
		return even ? "even" : "odd";
	}

	@Override
	public void remove() {
		throw new UnsupportedOperationException();
	}

}
